// /components/imageLinks.ts
// Array centralizado com links de imagens para usar no ImageCarousel

// Adicione quantas quiser — aqui vão exemplos reais do Unsplash
export const imageLinks = [
  "/imgs/imgsProjects_dayWater/imgs_dayWater (1).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (2).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (3).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (4).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (5).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (6).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (7).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (8).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (10).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (11).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (12).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (15).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (16).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (17).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (18).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (19).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (20).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (21).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (23).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (24).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (25).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (26).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (27).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (28).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (29).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (30).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (31).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (32).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (33).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (34).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (35).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (36).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (37).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (38).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (39).jpeg",
  "/imgs/imgsProjects_dayWater/imgs_dayWater (40).jpeg",
];
